pypi-list-classifiers: improve Python version check.
Before:

    $ python2.7 pypi-list-classifiers
    Traceback (most recent call last):
      File "pypi-list-classifiers", line 11, in <module>
        import urllib.request
    ImportError: No module named request

After:

    $ python2.7 pypi-list-classifiers
      File "pypi-list-classifiers", line 13
        rb''  # Python >= 3.3 is required
           ^
    SyntaxError: invalid syntax